version: '3.5'
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
  app: 
    build: .
    ports:
      - 8080:8080
  ai:
    build: ./app
    ports:
      - 12380:10380
