FROM python:3.7-alpine

LABEL maintainer="colinaaa"

RUN apk add --update tini

COPY . /app

WORKDIR /app
RUN apk add make automake gcc g++ subversion python3-dev 
#--repository http://mirrors.ustc.edu.cn/alpine/v3.9/main
# RUN pip install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl
RUN pip install  -r requirements.txt

EXPOSE 12380

ENTRYPOINT [ "/sbin/tini","--" ]
CMD [ "gunicorn" ,"-w 3","-b :12380","main:app"]
